/// Basit key-value çeviri sistemi. TR ve EN desteklenir.
class AppL10n {
  final String locale;
  const AppL10n(this.locale);

  String get(String key) => _strings[locale]?[key] ?? _strings['en']![key] ?? key;

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // Genel
      'app_name': 'Wallyt IPTV',
      'search': 'Search...',
      'settings': 'Settings',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'save': 'Save',
      'ok': 'OK',
      'delete': 'Delete',
      'close': 'Close',
      'loading': 'Loading...',
      'no_content': 'No content',
      'error': 'Error',
      // Tabs
      'tab_live': 'Live',
      'tab_movies': 'Movies',
      'tab_series': 'Series',
      'tab_favorites': 'Favorites',
      'tab_recents': 'Recents',
      'tab_channels': 'Channels',
      // Login
      'login_title': 'Xtream Codes Login',
      'login_server': 'Server URL',
      'login_username': 'Username',
      'login_password': 'Password',
      'login_connect': 'Connect',
      'login_m3u_url': 'M3U / M3U8 URL',
      'login_m3u_name': 'Playlist name (optional)',
      'login_load': 'Load Playlist',
      'login_saved': 'Saved Playlists',
      'login_failed': 'Login failed. Check server, username and password.',
      'login_m3u_failed': 'Could not load playlist. Check the URL.',
      // Player
      'player_channels': 'Channels',
      'player_movies': 'Movies',
      'player_catchup': 'Catch-up',
      'player_epg': 'Programme Guide',
      // Settings
      'settings_parental': 'Parental Control',
      'settings_parental_sub': 'Lock categories with a PIN',
      'settings_parental_enable': 'Enable Parental Control',
      'settings_parental_pin': 'Change PIN',
      'settings_parental_lock_cats': 'Lock Categories',
      'settings_theme': 'Appearance',
      'settings_theme_accent': 'Accent Color',
      'settings_theme_dark': 'Dark Mode',
      'settings_language': 'Language',
      'settings_stream': 'Playback',
      'settings_stream_mode': 'Stream Mode',
      'settings_buffer': 'Buffer (seconds)',
      'settings_hw_decode': 'Hardware Decode',
      'settings_storage': 'Storage',
      'settings_clear_history': 'Clear Watch History',
      'settings_clear_history_sub': 'Remove all recently watched channels',
      'settings_version': 'Version',
      // EPG
      'epg_now': 'Now',
      'epg_next': 'Next',
      'epg_no_data': 'No programme data',
      // Catch-up
      'catchup_title': 'TV Archive',
      'catchup_no_data': 'No archive available',
      // Parental
      'parental_enter_pin': 'Enter PIN',
      'parental_wrong_pin': 'Wrong PIN',
      'parental_new_pin': 'Set new 4-digit PIN',
      'parental_locked': 'This category is locked',
      // Stream mode
      'stream_auto': 'Auto',
      'stream_hls': 'HLS (.m3u8)',
      'stream_ts': 'TS (.ts)',
      // Update
      'update_available': 'Update Available',
      'update_download': 'Download',
      'update_later': 'Later',
    },
    'ar': {
      'app_name': 'Wallyt IPTV',
      'search': 'بحث...',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'ok': 'موافق',
      'delete': 'حذف',
      'close': 'إغلاق',
      'loading': 'جار التحميل...',
      'no_content': 'لا يوجد محتوى',
      'error': 'خطأ',
      'tab_live': 'مباشر',
      'tab_movies': 'أفلام',
      'tab_series': 'مسلسلات',
      'tab_favorites': 'المفضلة',
      'tab_recents': 'المشاهدة الأخيرة',
      'tab_channels': 'القنوات',
      'login_title': 'تسجيل الدخول Xtream',
      'login_server': 'رابط الخادم',
      'login_username': 'اسم المستخدم',
      'login_password': 'كلمة المرور',
      'login_connect': 'اتصال',
      'login_m3u_url': 'رابط M3U / M3U8',
      'login_m3u_name': 'اسم القائمة (اختياري)',
      'login_load': 'تحميل القائمة',
      'login_saved': 'القوائم المحفوظة',
      'login_failed': 'فشل تسجيل الدخول. تحقق من الخادم.',
      'login_m3u_failed': 'تعذر تحميل القائمة.',
      'player_channels': 'القنوات',
      'player_movies': 'أفلام',
      'player_catchup': 'أرشيف',
      'player_epg': 'دليل البرامج',
      'settings_parental': 'الرقابة الأبوية',
      'settings_parental_sub': 'قفل الفئات برمز PIN',
      'settings_parental_enable': 'تفعيل الرقابة الأبوية',
      'settings_parental_pin': 'تغيير PIN',
      'settings_parental_lock_cats': 'قفل الفئات',
      'settings_theme': 'المظهر',
      'settings_theme_accent': 'لون التمييز',
      'settings_theme_dark': 'الوضع الداكن',
      'settings_language': 'اللغة',
      'settings_stream': 'التشغيل',
      'settings_stream_mode': 'وضع البث',
      'settings_buffer': 'التخزين المؤقت (ثانية)',
      'settings_hw_decode': 'فك الترميز المادي',
      'settings_storage': 'التخزين',
      'settings_clear_history': 'مسح سجل المشاهدة',
      'settings_clear_history_sub': 'حذف القنوات التي شاهدتها مؤخراً',
      'settings_version': 'الإصدار',
      'epg_now': 'الآن',
      'epg_next': 'التالي',
      'epg_no_data': 'لا توجد بيانات برامج',
      'catchup_title': 'أرشيف التلفزيون',
      'catchup_no_data': 'لا يوجد أرشيف',
      'parental_enter_pin': 'أدخل PIN',
      'parental_wrong_pin': 'PIN خاطئ',
      'parental_new_pin': 'أدخل PIN مكون من 4 أرقام',
      'parental_locked': 'هذه الفئة مقفلة',
      'stream_auto': 'تلقائي',
      'stream_hls': 'HLS (.m3u8)',
      'stream_ts': 'TS (.ts)',
      'update_available': 'تحديث متوفر',
      'update_download': 'تحميل',
      'update_later': 'لاحقاً',
    },
    'hi': {
      'app_name': 'Wallyt IPTV',
      'search': 'खोजें...',
      'settings': 'सेटिंग्स',
      'logout': 'लॉग आउट',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'ok': 'ठीक है',
      'delete': 'हटाएं',
      'close': 'बंद करें',
      'loading': 'लोड हो रहा है...',
      'no_content': 'कोई सामग्री नहीं',
      'error': 'त्रुटि',
      'tab_live': 'लाइव',
      'tab_movies': 'फिल्में',
      'tab_series': 'सीरीज',
      'tab_favorites': 'पसंदीदा',
      'tab_recents': 'हाल ही में देखा',
      'tab_channels': 'चैनल',
      'login_title': 'Xtream Codes लॉगिन',
      'login_server': 'सर्वर URL',
      'login_username': 'उपयोगकर्ता नाम',
      'login_password': 'पासवर्ड',
      'login_connect': 'कनेक्ट करें',
      'login_m3u_url': 'M3U / M3U8 URL',
      'login_m3u_name': 'प्लेलिस्ट नाम (वैकल्पिक)',
      'login_load': 'प्लेलिस्ट लोड करें',
      'login_saved': 'सहेजी गई प्लेलिस्ट',
      'login_failed': 'लॉगिन विफल। सर्वर और पासवर्ड जांचें।',
      'login_m3u_failed': 'प्लेलिस्ट लोड नहीं हो सकी।',
      'player_channels': 'चैनल',
      'player_movies': 'फिल्में',
      'player_catchup': 'कैच-अप',
      'player_epg': 'प्रोग्राम गाइड',
      'settings_parental': 'अभिभावकीय नियंत्रण',
      'settings_parental_sub': 'PIN से श्रेणियां लॉक करें',
      'settings_parental_enable': 'अभिभावकीय नियंत्रण सक्षम करें',
      'settings_parental_pin': 'PIN बदलें',
      'settings_parental_lock_cats': 'श्रेणियां लॉक करें',
      'settings_theme': 'स्वरूप',
      'settings_theme_accent': 'एक्सेंट रंग',
      'settings_theme_dark': 'डार्क मोड',
      'settings_language': 'भाषा',
      'settings_stream': 'प्लेबैक',
      'settings_stream_mode': 'स्ट्रीम मोड',
      'settings_buffer': 'बफर (सेकंड)',
      'settings_hw_decode': 'हार्डवेयर डीकोड',
      'settings_storage': 'संग्रहण',
      'settings_clear_history': 'देखने का इतिहास साफ करें',
      'settings_clear_history_sub': 'हाल ही में देखे गए चैनल हटाएं',
      'settings_version': 'संस्करण',
      'epg_now': 'अभी',
      'epg_next': 'अगला',
      'epg_no_data': 'कोई प्रोग्राम डेटा नहीं',
      'catchup_title': 'TV आर्काइव',
      'catchup_no_data': 'कोई आर्काइव उपलब्ध नहीं',
      'parental_enter_pin': 'PIN दर्ज करें',
      'parental_wrong_pin': 'गलत PIN',
      'parental_new_pin': '4 अंकों का PIN सेट करें',
      'parental_locked': 'यह श्रेणी लॉक है',
      'stream_auto': 'स्वचालित',
      'stream_hls': 'HLS (.m3u8)',
      'stream_ts': 'TS (.ts)',
      'update_available': 'अपडेट उपलब्ध है',
      'update_download': 'डाउनलोड',
      'update_later': 'बाद में',
    },
    'ur': {
      'app_name': 'Wallyt IPTV',
      'search': 'تلاش کریں...',
      'settings': 'ترتیبات',
      'logout': 'لاگ آؤٹ',
      'cancel': 'منسوخ',
      'save': 'محفوظ کریں',
      'ok': 'ٹھیک ہے',
      'delete': 'حذف کریں',
      'close': 'بند کریں',
      'loading': 'لوڈ ہو رہا ہے...',
      'no_content': 'کوئی مواد نہیں',
      'error': 'خطا',
      'tab_live': 'لائیو',
      'tab_movies': 'فلمیں',
      'tab_series': 'سیریز',
      'tab_favorites': 'پسندیدہ',
      'tab_recents': 'حال ہی میں دیکھا',
      'tab_channels': 'چینلز',
      'login_title': 'Xtream Codes لاگ ان',
      'login_server': 'سرور URL',
      'login_username': 'صارف نام',
      'login_password': 'پاس ورڈ',
      'login_connect': 'جڑیں',
      'login_m3u_url': 'M3U / M3U8 URL',
      'login_m3u_name': 'پلے لسٹ نام (اختیاری)',
      'login_load': 'پلے لسٹ لوڈ کریں',
      'login_saved': 'محفوظ پلے لسٹس',
      'login_failed': 'لاگ ان ناکام۔ سرور اور پاس ورڈ چیک کریں۔',
      'login_m3u_failed': 'پلے لسٹ لوڈ نہیں ہو سکی۔',
      'player_channels': 'چینلز',
      'player_movies': 'فلمیں',
      'player_catchup': 'کیچ-اپ',
      'player_epg': 'پروگرام گائیڈ',
      'settings_parental': 'والدین کا کنٹرول',
      'settings_parental_sub': 'PIN سے زمرے لاک کریں',
      'settings_parental_enable': 'والدین کا کنٹرول فعال کریں',
      'settings_parental_pin': 'PIN تبدیل کریں',
      'settings_parental_lock_cats': 'زمرے لاک کریں',
      'settings_theme': 'ظاہری شکل',
      'settings_theme_accent': 'ایکسینٹ رنگ',
      'settings_theme_dark': 'ڈارک موڈ',
      'settings_language': 'زبان',
      'settings_stream': 'پلے بیک',
      'settings_stream_mode': 'سٹریم موڈ',
      'settings_buffer': 'بفر (سیکنڈ)',
      'settings_hw_decode': 'ہارڈویئر ڈیکوڈ',
      'settings_storage': 'اسٹوریج',
      'settings_clear_history': 'دیکھنے کی تاریخ صاف کریں',
      'settings_clear_history_sub': 'حال ہی میں دیکھے گئے چینل ہٹائیں',
      'settings_version': 'ورژن',
      'epg_now': 'ابھی',
      'epg_next': 'اگلا',
      'epg_no_data': 'کوئی پروگرام ڈیٹا نہیں',
      'catchup_title': 'TV آرکائیو',
      'catchup_no_data': 'کوئی آرکائیو دستیاب نہیں',
      'parental_enter_pin': 'PIN درج کریں',
      'parental_wrong_pin': 'غلط PIN',
      'parental_new_pin': '4 ہندسوں کا PIN سیٹ کریں',
      'parental_locked': 'یہ زمرہ لاک ہے',
      'stream_auto': 'خودکار',
      'stream_hls': 'HLS (.m3u8)',
      'stream_ts': 'TS (.ts)',
      'update_available': 'اپڈیٹ دستیاب ہے',
      'update_download': 'ڈاؤن لوڈ',
      'update_later': 'بعد میں',
    },
    'id': {
      'app_name': 'Wallyt IPTV',
      'search': 'Cari...',
      'settings': 'Pengaturan',
      'logout': 'Keluar',
      'cancel': 'Batal',
      'save': 'Simpan',
      'ok': 'OK',
      'delete': 'Hapus',
      'close': 'Tutup',
      'loading': 'Memuat...',
      'no_content': 'Tidak ada konten',
      'error': 'Kesalahan',
      'tab_live': 'Live',
      'tab_movies': 'Film',
      'tab_series': 'Serial',
      'tab_favorites': 'Favorit',
      'tab_recents': 'Terakhir Ditonton',
      'tab_channels': 'Saluran',
      'login_title': 'Login Xtream Codes',
      'login_server': 'URL Server',
      'login_username': 'Nama Pengguna',
      'login_password': 'Kata Sandi',
      'login_connect': 'Hubungkan',
      'login_m3u_url': 'URL M3U / M3U8',
      'login_m3u_name': 'Nama playlist (opsional)',
      'login_load': 'Muat Playlist',
      'login_saved': 'Playlist Tersimpan',
      'login_failed': 'Login gagal. Periksa server dan kata sandi.',
      'login_m3u_failed': 'Gagal memuat playlist.',
      'player_channels': 'Saluran',
      'player_movies': 'Film',
      'player_catchup': 'Tayangan Ulang',
      'player_epg': 'Panduan Program',
      'settings_parental': 'Kontrol Orang Tua',
      'settings_parental_sub': 'Kunci kategori dengan PIN',
      'settings_parental_enable': 'Aktifkan Kontrol Orang Tua',
      'settings_parental_pin': 'Ubah PIN',
      'settings_parental_lock_cats': 'Kunci Kategori',
      'settings_theme': 'Tampilan',
      'settings_theme_accent': 'Warna Aksen',
      'settings_theme_dark': 'Mode Gelap',
      'settings_language': 'Bahasa',
      'settings_stream': 'Pemutaran',
      'settings_stream_mode': 'Mode Stream',
      'settings_buffer': 'Buffer (detik)',
      'settings_hw_decode': 'Dekode Hardware',
      'settings_storage': 'Penyimpanan',
      'settings_clear_history': 'Hapus Riwayat Tonton',
      'settings_clear_history_sub': 'Hapus semua saluran yang baru ditonton',
      'settings_version': 'Versi',
      'epg_now': 'Sekarang',
      'epg_next': 'Berikutnya',
      'epg_no_data': 'Tidak ada data program',
      'catchup_title': 'Arsip TV',
      'catchup_no_data': 'Tidak ada arsip',
      'parental_enter_pin': 'Masukkan PIN',
      'parental_wrong_pin': 'PIN salah',
      'parental_new_pin': 'Atur PIN 4 digit',
      'parental_locked': 'Kategori ini terkunci',
      'stream_auto': 'Otomatis',
      'stream_hls': 'HLS (.m3u8)',
      'stream_ts': 'TS (.ts)',
      'update_available': 'Pembaruan Tersedia',
      'update_download': 'Unduh',
      'update_later': 'Nanti',
    },
    'bn': {
      'app_name': 'Wallyt IPTV',
      'search': 'খুঁজুন...',
      'settings': 'সেটিংস',
      'logout': 'লগ আউট',
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ করুন',
      'ok': 'ঠিক আছে',
      'delete': 'মুছুন',
      'close': 'বন্ধ করুন',
      'loading': 'লোড হচ্ছে...',
      'no_content': 'কোনো বিষয়বস্তু নেই',
      'error': 'ত্রুটি',
      'tab_live': 'লাইভ',
      'tab_movies': 'চলচ্চিত্র',
      'tab_series': 'সিরিজ',
      'tab_favorites': 'পছন্দসই',
      'tab_recents': 'সম্প্রতি দেখা',
      'tab_channels': 'চ্যানেল',
      'login_title': 'Xtream Codes লগইন',
      'login_server': 'সার্ভার URL',
      'login_username': 'ব্যবহারকারীর নাম',
      'login_password': 'পাসওয়ার্ড',
      'login_connect': 'সংযোগ করুন',
      'login_m3u_url': 'M3U / M3U8 URL',
      'login_m3u_name': 'প্লেলিস্ট নাম (ঐচ্ছিক)',
      'login_load': 'প্লেলিস্ট লোড করুন',
      'login_saved': 'সংরক্ষিত প্লেলিস্ট',
      'login_failed': 'লগইন ব্যর্থ। সার্ভার ও পাসওয়ার্ড যাচাই করুন।',
      'login_m3u_failed': 'প্লেলিস্ট লোড করা যায়নি।',
      'player_channels': 'চ্যানেল',
      'player_movies': 'চলচ্চিত্র',
      'player_catchup': 'ক্যাচ-আপ',
      'player_epg': 'প্রোগ্রাম গাইড',
      'settings_parental': 'অভিভাবকীয় নিয়ন্ত্রণ',
      'settings_parental_sub': 'PIN দিয়ে বিভাগ লক করুন',
      'settings_parental_enable': 'অভিভাবকীয় নিয়ন্ত্রণ সক্রিয় করুন',
      'settings_parental_pin': 'PIN পরিবর্তন করুন',
      'settings_parental_lock_cats': 'বিভাগ লক করুন',
      'settings_theme': 'চেহারা',
      'settings_theme_accent': 'অ্যাকসেন্ট রঙ',
      'settings_theme_dark': 'ডার্ক মোড',
      'settings_language': 'ভাষা',
      'settings_stream': 'প্লেব্যাক',
      'settings_stream_mode': 'স্ট্রিম মোড',
      'settings_buffer': 'বাফার (সেকেন্ড)',
      'settings_hw_decode': 'হার্ডওয়্যার ডিকোড',
      'settings_storage': 'স্টোরেজ',
      'settings_clear_history': 'দেখার ইতিহাস মুছুন',
      'settings_clear_history_sub': 'সম্প্রতি দেখা চ্যানেলগুলি সরান',
      'settings_version': 'সংস্করণ',
      'epg_now': 'এখন',
      'epg_next': 'পরবর্তী',
      'epg_no_data': 'কোনো প্রোগ্রাম ডেটা নেই',
      'catchup_title': 'TV আর্কাইভ',
      'catchup_no_data': 'কোনো আর্কাইভ নেই',
      'parental_enter_pin': 'PIN লিখুন',
      'parental_wrong_pin': 'ভুল PIN',
      'parental_new_pin': '4 সংখ্যার PIN সেট করুন',
      'parental_locked': 'এই বিভাগটি লক করা আছে',
      'stream_auto': 'স্বয়ংক্রিয়',
      'stream_hls': 'HLS (.m3u8)',
      'stream_ts': 'TS (.ts)',
      'update_available': 'আপডেট উপলব্ধ',
      'update_download': 'ডাউনলোড',
      'update_later': 'পরে',
    },
    'tr': {
      // Genel
      'app_name': 'Wallyt IPTV',
      'search': 'Ara...',
      'settings': 'Ayarlar',
      'logout': 'Çıkış',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'ok': 'Tamam',
      'delete': 'Sil',
      'close': 'Kapat',
      'loading': 'Yükleniyor...',
      'no_content': 'İçerik yok',
      'error': 'Hata',
      // Tabs
      'tab_live': 'Canlı',
      'tab_movies': 'Filmler',
      'tab_series': 'Diziler',
      'tab_favorites': 'Favoriler',
      'tab_recents': 'Son İzlenenler',
      'tab_channels': 'Kanallar',
      // Login
      'login_title': 'Xtream Codes Giriş',
      'login_server': 'Sunucu URL',
      'login_username': 'Kullanıcı Adı',
      'login_password': 'Şifre',
      'login_connect': 'Bağlan',
      'login_m3u_url': 'M3U / M3U8 URL',
      'login_m3u_name': 'Playlist adı (isteğe bağlı)',
      'login_load': 'Playlist Yükle',
      'login_saved': 'Kayıtlı Listeler',
      'login_failed': 'Giriş başarısız. Sunucu, kullanıcı adı ve şifreyi kontrol edin.',
      'login_m3u_failed': 'Playlist yüklenemedi. URL\'yi kontrol edin.',
      // Player
      'player_channels': 'Kanallar',
      'player_movies': 'Filmler',
      'player_catchup': 'Arşiv',
      'player_epg': 'Program Rehberi',
      // Settings
      'settings_parental': 'Ebeveyn Denetimi',
      'settings_parental_sub': 'PIN ile kategorileri kilitle',
      'settings_parental_enable': 'Ebeveyn Denetimini Etkinleştir',
      'settings_parental_pin': 'PIN Değiştir',
      'settings_parental_lock_cats': 'Kategorileri Kilitle',
      'settings_theme': 'Görünüm',
      'settings_theme_accent': 'Renk Teması',
      'settings_theme_dark': 'Karanlık Mod',
      'settings_language': 'Dil',
      'settings_stream': 'Oynatma',
      'settings_stream_mode': 'Yayın Modu',
      'settings_buffer': 'Tampon (saniye)',
      'settings_hw_decode': 'Donanım Kodçözücü',
      'settings_storage': 'Depolama',
      'settings_clear_history': 'İzleme Geçmişini Temizle',
      'settings_clear_history_sub': 'Son izlenen kanalları kaldır',
      'settings_version': 'Sürüm',
      // EPG
      'epg_now': 'Şu An',
      'epg_next': 'Sonraki',
      'epg_no_data': 'Program verisi yok',
      // Catch-up
      'catchup_title': 'TV Arşivi',
      'catchup_no_data': 'Arşiv mevcut değil',
      // Parental
      'parental_enter_pin': 'PIN Girin',
      'parental_wrong_pin': 'Yanlış PIN',
      'parental_new_pin': '4 haneli PIN belirleyin',
      'parental_locked': 'Bu kategori kilitli',
      // Stream mode
      'stream_auto': 'Otomatik',
      'stream_hls': 'HLS (.m3u8)',
      'stream_ts': 'TS (.ts)',
      // Update
      'update_available': 'Güncelleme Mevcut',
      'update_download': 'İndir',
      'update_later': 'Sonra',
    },
  };
}
