// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs02Mk5C009RyplcBDZtYD0RDU8KbfyII',
    appId: '1:938825970734:web:dddadb18744e998c729bbf',
    messagingSenderId: '938825970734',
    projectId: 'iptv-player-az1',
    authDomain: 'iptv-player-az1.firebaseapp.com',
    storageBucket: 'iptv-player-az1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJ5YfhvUTQ2FqiYBrwr6X60VK0XcR2eE',
    appId: '1:938825970734:android:22c1dc83ea58d182729bbf',
    messagingSenderId: '938825970734',
    projectId: 'iptv-player-az1',
    storageBucket: 'iptv-player-az1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhc_lTe_frr00ZjU2PZthf-vx34Q7WHBA',
    appId: '1:938825970734:ios:d95bb889553915d3729bbf',
    messagingSenderId: '938825970734',
    projectId: 'iptv-player-az1',
    storageBucket: 'iptv-player-az1.firebasestorage.app',
    iosBundleId: 'com.example.iptvPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhc_lTe_frr00ZjU2PZthf-vx34Q7WHBA',
    appId: '1:938825970734:ios:d95bb889553915d3729bbf',
    messagingSenderId: '938825970734',
    projectId: 'iptv-player-az1',
    storageBucket: 'iptv-player-az1.firebasestorage.app',
    iosBundleId: 'com.example.iptvPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs02Mk5C009RyplcBDZtYD0RDU8KbfyII',
    appId: '1:938825970734:web:314b5e948cae82b0729bbf',
    messagingSenderId: '938825970734',
    projectId: 'iptv-player-az1',
    authDomain: 'iptv-player-az1.firebaseapp.com',
    storageBucket: 'iptv-player-az1.firebasestorage.app',
  );
}
